using System;
using Microsoft.CodeAnalysis;

namespace SourceGeneratorExamples.Library.Services.BuilderServices
{
    public abstract class BuilderService : IBuilderService
    {
        protected static readonly DiagnosticDescriptor CannotInferBuilderPropertyFromArgumentDiagnostic =
            new("DBG002",
                "Cannot infer property name to use for constructor parameter (using constructor with most parameters)",
                "Mark class {0} as partial in order to generate data builders for it", "BuilderGenerator",
                DiagnosticSeverity.Error, true);

        protected static readonly string GeneratedByDataBuilderGeneratorPreamble =
            @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the source code generator tool.
// </auto-generated>
// ------------------------------------------------------------------------------
            ".Replace("\r\n", "\n").Replace("\n", Environment.NewLine); 
    }
}